config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to:'todos#create'
  get 'todos/list', to: 'todos#list' , as:'list_todo'
  get 'todos/:id',to:'todos#show' ,as:'todo'
  get 'todos/:id/edit', to:'todos#edit', as:'edit_todo'
  patch 'todos/:id' ,to:'todos#update'
  delete 'todos/:id' , to:'todos#destroy'
  post  'todos/:id/completed', to:'todos#completed', as:'completed_todo' 
  
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :find_todo , only: [:edit, :update, :show, :destroy,:completed]
    def index
        @todos = Todo.all   
       
    end
    def new
        @todo = Todo.new
    end
    def create
        @todo = Todo.new(todo_params)
        @todo.save
        redirect_to todos_path
    end   

    def show


    end
    def edit
        

    end
    def update
       
        @todo.update(todo_params)
        redirect_to todos_path
    end
    def destroy

        @todo.destroy
        redirect_to todos_path
    end
    def completed
        @todo.completed=true
        @todo.save
        redirect_to todos_path
    end

    def list
        @todos = Todo.all
       
    end
    
    private
    def todo_params
        params.require(:todo).permit(:description,:completed)
    end
    def find_todo
        @todo =Todo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
  
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-fixed-top  navbar-dark bg-dark sticky-top">
      <a class="nav-link" style="color:white"><strong>ToDo</strong></a>
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
           <li class="nav-item active">
             <%= link_to "Home", todos_path ,class:"nav-link"%>
           </li>
           <li class="nav-item active">
             <%= link_to "Ver Lista", list_todo_path ,class:"nav-link"%>
           </li>
           <li class="nav-item active">
             <%= link_to "nuevo ToDo", todos_new_path ,class:"nav-link"%>
           </li>
         </ul>
        </div><!-- /.navbar-collapse -->
   </div>
</nav>
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<br>
<br>
<br>
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <%=form_with(model:@todo,local:true) do|f|%>
            <%=f.label :description ,"Ingrese una descipción"%>
            <%=f.text_area :description%>
            <%=f.label :completed ,"la tarea está realizada"%>
            <%= f.check_box :completed %>            
            <%=f.submit "Enviar"%>
        <%end%>
    </div> 
</div>   

app/views/todos/edit.html.erb
<%=  render  "form" %>

app/views/todos/index.html.erb
<br>
<br>
<br>
 <div class="card" style="width: 18rem;">
    
        <%@todos.each do|todo|%>
            <div class="card-body">
                <h1 class="card-title"><%=todo.description%></h1>
                <h1 class="card-title"><%=todo.completed%></h1>
                <%= link_to "Ver", todo_path(todo), class:"btn btn-primary"%>
                <%= link_to "Edit", edit_todo_path(todo), class:"btn btn-warning"%>
                <%= link_to "borrar", todo,method: :delete ,class:"btn btn-danger"%>
                <%= link_to "completed", completed_todo_path(todo),method: :post ,class:"btn btn-success"%>
            </div>
        <%end%>
    
</div>

app/views/todos/list.html.erb
<div class="row">
    <div class="col-md-6 col-lg-6- col-sm-6 col-xs-6">
        <h1>ToDo NO completados</h1>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                
                    <%@todos.each do|todo|%>
                        <% if todo.completed == false %>
                            <h1 class="card-title"><%=todo.description%></h1>
                            <%= link_to "Ver", todo_path(todo), class:"btn btn-primary"%>
                            <%= link_to "Edit", edit_todo_path(todo), class:"btn btn-warning"%>
                            <%= link_to "borrar", todo,method: :delete ,class:"btn btn-danger"%>
                            <%= link_to "completed", completed_todo_path(todo),method: :post ,class:"btn btn-success"%>
                        <%end%>
                <%end%>
        </div>
    </div>
    </div>
    <div class="col-md-6 col-lg-6- col-sm-6 col-xs-6">
        <h1>ToDo  completados</h1>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <%@todos.each do|todo|%>
                    <%if todo.completed == true%>
                        <h1 class="card-title"><%=todo.description%></h1>

                        <%= link_to "Ver", todo_path(todo), class:"btn btn-primary"%>
                        <%= link_to "Edit", edit_todo_path(todo), class:"btn btn-warning"%>
                        <%= link_to "borrar", todo,method: :delete ,class:"btn btn-danger"%>
                        <%= link_to "completed", completed_todo_path(todo),method: :post ,class:"btn btn-success"%>
                        <%end%>
                <%end%>
            </div>
        </div>
    </div>
</div>

app/views/todos/new.html.erb
<%=  render  "form" %>

app/views/todos/show.html.erb
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <%=label :description ,"tarea"%>
        <h1> <%=@todo.description%></h1>
        <%=label :completed ,"Estado de la Tarea: "%>
        <p> <%=@todo.completed%></p>
        <p>creado hace_<%=time_ago_in_words @todo.created_at%> </p> 
    </div>
</div>